// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDedZA7zul9zWfCIf2jfXsLC1k9QSlJr8',
    appId: '1:124193308668:web:ba3687ecd9e76e00233c79',
    messagingSenderId: '124193308668',
    projectId: 'quiz4-15028',
    authDomain: 'quiz4-15028.firebaseapp.com',
    storageBucket: 'quiz4-15028.appspot.com',
    measurementId: 'G-ED6D7VFB71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF029fK7XFrBDSQm1j4WSe2dnXK2g0zP4',
    appId: '1:124193308668:android:80af6dc0301042cb233c79',
    messagingSenderId: '124193308668',
    projectId: 'quiz4-15028',
    storageBucket: 'quiz4-15028.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDedZA7zul9zWfCIf2jfXsLC1k9QSlJr8',
    appId: '1:124193308668:web:82b283fba41d4250233c79',
    messagingSenderId: '124193308668',
    projectId: 'quiz4-15028',
    authDomain: 'quiz4-15028.firebaseapp.com',
    storageBucket: 'quiz4-15028.appspot.com',
    measurementId: 'G-KF70Q0DVHJ',
  );
}
